import Head from 'next/head';
import { Bar } from '../components/Bar';
import Image from '../components/Image';
import Nav from '../components/Nav';
import { ToastContainer } from 'react-toastify';

export default function Home() {
  return (
    <>
      <Head>
        <title>New Tab</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Bar Engine='DuckDuckGo' />
      <Nav className='absolute bottom-0 right-0' />
      <Image />

      <ToastContainer />
    </>
  );
}
