import Head from 'next/head';
import { Bar } from '../engines/Bar';
import Image from '../components/Image';
import Nav from '../components/Nav';
import { ToastContainer } from 'react-toastify';
import notify from '../utils/notification';

export default function Home() {
  return (
    <>
      <Head>
        <title>New Tab</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Bar />
      <Nav className='absolute bottom-0 right-0' />
      <Image />

      <ToastContainer />
    </>
  );
}
